command: ["bash", "start.sh"]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "sql-warehouse"
  - name: RISKBRICKS_AGENT_ENDPOINT
    valueFrom: "serving-endpoint"
